name: update-readme

on:
  push:

jobs:
  update-readme-job:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v2
      - name: Run update-readme.sh script
        run: ./update-readme.sh ${{ github.actor }}
