name: update-readme

on:
  push:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Run update-readme.sh script
      - run: ./update-readme.sh ${{ github.actor }}
