name: update-readme

on:
  push:

jobs:
  update-readme-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run update-readme.sh script
        run: ./update-readme.sh ${{ github.actor }}
      - name: Push new changes to git
        run: git add README.md | git commit -m"Updated README.md"
