name: update-readme

on:
  push:

jobs:
  update-readme-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Run update-readme.sh script
        run: ./update-readme.sh ${{ github.event.pusher.name }}

      - name: Push to git
        run: |
          git config --global user.name ${{ github.event.pusher.name }}
          git config --global user.email ${{ github.event.pusher.email }}
          git add README.md
          git commit -m"Updated README.md"
          git push

